/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthToken model module.
 * @module model/AuthToken
 * @version 0.1.0
 */
export class AuthToken {
  /**
   * Constructs a new <code>AuthToken</code>.
   * @alias module:model/AuthToken
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthToken</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthToken} obj Optional instance to populate.
   * @return {module:model/AuthToken} The populated <code>AuthToken</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthToken();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('expiresAt'))
        obj.expiresAt = ApiClient.convertToType(data['expiresAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} token
 */
AuthToken.prototype.token = undefined;

/**
 * @member {Date} expiresAt
 */
AuthToken.prototype.expiresAt = undefined;

