/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthEmailUpdateRequestRequest model module.
 * @module model/AuthEmailUpdateRequestRequest
 * @version 0.1.0
 */
class AuthEmailUpdateRequestRequest {
    /**
     * Constructs a new <code>AuthEmailUpdateRequestRequest</code>.
     * @alias module:model/AuthEmailUpdateRequestRequest
     * @param email {Object} 
     * @param emailConf {Object} 
     */
    constructor(email, emailConf) { 
        
        AuthEmailUpdateRequestRequest.initialize(this, email, emailConf);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, emailConf) { 
        obj['email'] = email;
        obj['emailConf'] = emailConf;
    }

    /**
     * Constructs a <code>AuthEmailUpdateRequestRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthEmailUpdateRequestRequest} obj Optional instance to populate.
     * @return {module:model/AuthEmailUpdateRequestRequest} The populated <code>AuthEmailUpdateRequestRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthEmailUpdateRequestRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], Object);
            }
            if (data.hasOwnProperty('emailConf')) {
                obj['emailConf'] = ApiClient.convertToType(data['emailConf'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthEmailUpdateRequestRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthEmailUpdateRequestRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthEmailUpdateRequestRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

AuthEmailUpdateRequestRequest.RequiredProperties = ["email", "emailConf"];

/**
 * @member {Object} email
 */
AuthEmailUpdateRequestRequest.prototype['email'] = undefined;

/**
 * @member {Object} emailConf
 */
AuthEmailUpdateRequestRequest.prototype['emailConf'] = undefined;






export default AuthEmailUpdateRequestRequest;

