/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResPublicCredentialCard from './ResPublicCredentialCard';

/**
 * The CredentialCardsGetOne200Response model module.
 * @module model/CredentialCardsGetOne200Response
 * @version 0.1.0
 */
class CredentialCardsGetOne200Response {
    /**
     * Constructs a new <code>CredentialCardsGetOne200Response</code>.
     * @alias module:model/CredentialCardsGetOne200Response
     */
    constructor() { 
        
        CredentialCardsGetOne200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CredentialCardsGetOne200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CredentialCardsGetOne200Response} obj Optional instance to populate.
     * @return {module:model/CredentialCardsGetOne200Response} The populated <code>CredentialCardsGetOne200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CredentialCardsGetOne200Response();

            if (data.hasOwnProperty('credentialCard')) {
                obj['credentialCard'] = ResPublicCredentialCard.constructFromObject(data['credentialCard']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CredentialCardsGetOne200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CredentialCardsGetOne200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `credentialCard`
        if (data['credentialCard']) { // data not null
          ResPublicCredentialCard.validateJSON(data['credentialCard']);
        }

        return true;
    }


}



/**
 * @member {module:model/ResPublicCredentialCard} credentialCard
 */
CredentialCardsGetOne200Response.prototype['credentialCard'] = undefined;






export default CredentialCardsGetOne200Response;

