/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CredentialCardIdExpirationBody model module.
 * @module model/CredentialCardIdExpirationBody
 * @version 0.1.0
 */
export class CredentialCardIdExpirationBody {
  /**
   * Constructs a new <code>CredentialCardIdExpirationBody</code>.
   * @alias module:model/CredentialCardIdExpirationBody
   * @class
   * @param expirationDate {Date} 
   */
  constructor(expirationDate) {
    this.expirationDate = expirationDate;
  }

  /**
   * Constructs a <code>CredentialCardIdExpirationBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CredentialCardIdExpirationBody} obj Optional instance to populate.
   * @return {module:model/CredentialCardIdExpirationBody} The populated <code>CredentialCardIdExpirationBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CredentialCardIdExpirationBody();
      if (data.hasOwnProperty('expirationDate'))
        obj.expirationDate = ApiClient.convertToType(data['expirationDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Date} expirationDate
 */
CredentialCardIdExpirationBody.prototype.expirationDate = undefined;

