/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocsProfileDocKeyBody model module.
 * @module model/DocsProfileDocKeyBody
 * @version 0.1.0
 */
export class DocsProfileDocKeyBody {
  /**
   * Constructs a new <code>DocsProfileDocKeyBody</code>.
   * @alias module:model/DocsProfileDocKeyBody
   * @class
   * @param docName {String} 
   * @param docFile {Blob} 
   */
  constructor(docName, docFile) {
    this.docName = docName;
    this.docFile = docFile;
  }

  /**
   * Constructs a <code>DocsProfileDocKeyBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocsProfileDocKeyBody} obj Optional instance to populate.
   * @return {module:model/DocsProfileDocKeyBody} The populated <code>DocsProfileDocKeyBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocsProfileDocKeyBody();
      if (data.hasOwnProperty('docName'))
        obj.docName = ApiClient.convertToType(data['docName'], 'String');
      if (data.hasOwnProperty('docFile'))
        obj.docFile = ApiClient.convertToType(data['docFile'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {String} docName
 */
DocsProfileDocKeyBody.prototype.docName = undefined;

/**
 * @member {Blob} docFile
 */
DocsProfileDocKeyBody.prototype.docFile = undefined;

