/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AuthToken} from './AuthToken';

/**
 * The InlineResponse200AuthTokens model module.
 * @module model/InlineResponse200AuthTokens
 * @version 0.1.0
 */
export class InlineResponse200AuthTokens {
  /**
   * Constructs a new <code>InlineResponse200AuthTokens</code>.
   * @alias module:model/InlineResponse200AuthTokens
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse200AuthTokens</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200AuthTokens} obj Optional instance to populate.
   * @return {module:model/InlineResponse200AuthTokens} The populated <code>InlineResponse200AuthTokens</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse200AuthTokens();
      if (data.hasOwnProperty('refresh'))
        obj.refresh = AuthToken.constructFromObject(data['refresh']);
      if (data.hasOwnProperty('auth'))
        obj.auth = AuthToken.constructFromObject(data['auth']);
    }
    return obj;
  }
}

/**
 * @member {module:model/AuthToken} refresh
 */
InlineResponse200AuthTokens.prototype.refresh = undefined;

/**
 * @member {module:model/AuthToken} auth
 */
InlineResponse200AuthTokens.prototype.auth = undefined;

