/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ResShopOrderPayment} from './ResShopOrderPayment';

/**
 * The InlineResponse20020 model module.
 * @module model/InlineResponse20020
 * @version 0.1.0
 */
export class InlineResponse20020 {
  /**
   * Constructs a new <code>InlineResponse20020</code>.
   * @alias module:model/InlineResponse20020
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20020</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20020} obj Optional instance to populate.
   * @return {module:model/InlineResponse20020} The populated <code>InlineResponse20020</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20020();
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], [ResShopOrderPayment]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ResShopOrderPayment>} order
 */
InlineResponse20020.prototype.order = undefined;

