/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResMember from './ResMember';

/**
 * The MembersList200Response model module.
 * @module model/MembersList200Response
 * @version 0.1.0
 */
class MembersList200Response {
    /**
     * Constructs a new <code>MembersList200Response</code>.
     * @alias module:model/MembersList200Response
     */
    constructor() { 
        
        MembersList200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MembersList200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MembersList200Response} obj Optional instance to populate.
     * @return {module:model/MembersList200Response} The populated <code>MembersList200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MembersList200Response();

            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [ResMember]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MembersList200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MembersList200Response</code>.
     */
    static validateJSON(data) {
        if (data['members']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['members'])) {
                throw new Error("Expected the field `members` to be an array in the JSON data but got " + data['members']);
            }
            // validate the optional field `members` (array)
            for (const item of data['members']) {
                ResMember.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ResMember>} members
 */
MembersList200Response.prototype['members'] = undefined;






export default MembersList200Response;

