/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MemberGender.
* @enum {}
* @readonly
*/
export default class MemberGender {
    
        /**
         * value: "MALE"
         * @const
         */
        "MALE" = "MALE";

    
        /**
         * value: "FEMALE"
         * @const
         */
        "FEMALE" = "FEMALE";

    

    /**
    * Returns a <code>MemberGender</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MemberGender} The enum <code>MemberGender</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

