/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MembershipDocKey.
* @enum {}
* @readonly
*/
export default class MembershipDocKey {
    
        /**
         * value: "declarationAmericans"
         * @const
         */
        "declarationAmericans" = "declarationAmericans";

    
        /**
         * value: "declarationImmigrants"
         * @const
         */
        "declarationImmigrants" = "declarationImmigrants";

    
        /**
         * value: "declarationFederalPersons"
         * @const
         */
        "declarationFederalPersons" = "declarationFederalPersons";

    
        /**
         * value: "declarationPoliticalStatus"
         * @const
         */
        "declarationPoliticalStatus" = "declarationPoliticalStatus";

    
        /**
         * value: "birthRecord"
         * @const
         */
        "birthRecord" = "birthRecord";

    
        /**
         * value: "witnessTestimony1"
         * @const
         */
        "witnessTestimony1" = "witnessTestimony1";

    
        /**
         * value: "witnessTestimony2"
         * @const
         */
        "witnessTestimony2" = "witnessTestimony2";

    
        /**
         * value: "voterCancellation"
         * @const
         */
        "voterCancellation" = "voterCancellation";

    
        /**
         * value: "revocationTaxes1"
         * @const
         */
        "revocationTaxes1" = "revocationTaxes1";

    
        /**
         * value: "revocationTaxes2"
         * @const
         */
        "revocationTaxes2" = "revocationTaxes2";

    
        /**
         * value: "deedReconveyance"
         * @const
         */
        "deedReconveyance" = "deedReconveyance";

    
        /**
         * value: "certAssumedName"
         * @const
         */
        "certAssumedName" = "certAssumedName";

    
        /**
         * value: "actExpatriation1"
         * @const
         */
        "actExpatriation1" = "actExpatriation1";

    
        /**
         * value: "actExpatriation2"
         * @const
         */
        "actExpatriation2" = "actExpatriation2";

    
        /**
         * value: "actExpatriation3"
         * @const
         */
        "actExpatriation3" = "actExpatriation3";

    
        /**
         * value: "cancellationPowerAttorney"
         * @const
         */
        "cancellationPowerAttorney" = "cancellationPowerAttorney";

    
        /**
         * value: "foreignSovereignImmunitiesAct"
         * @const
         */
        "foreignSovereignImmunitiesAct" = "foreignSovereignImmunitiesAct";

    
        /**
         * value: "dnaParamountClaim"
         * @const
         */
        "dnaParamountClaim" = "dnaParamountClaim";

    
        /**
         * value: "militarySeverance"
         * @const
         */
        "militarySeverance" = "militarySeverance";

    
        /**
         * value: "commonCarryDeclaration"
         * @const
         */
        "commonCarryDeclaration" = "commonCarryDeclaration";

    
        /**
         * value: "feeSchedule"
         * @const
         */
        "feeSchedule" = "feeSchedule";

    
        /**
         * value: "lineageTreaty"
         * @const
         */
        "lineageTreaty" = "lineageTreaty";

    
        /**
         * value: "marriageRecord"
         * @const
         */
        "marriageRecord" = "marriageRecord";

    
        /**
         * value: "babyDeed1"
         * @const
         */
        "babyDeed1" = "babyDeed1";

    
        /**
         * value: "babyDeed2"
         * @const
         */
        "babyDeed2" = "babyDeed2";

    
        /**
         * value: "babyDeed3"
         * @const
         */
        "babyDeed3" = "babyDeed3";

    
        /**
         * value: "babyDeed4"
         * @const
         */
        "babyDeed4" = "babyDeed4";

    
        /**
         * value: "babyDeed5"
         * @const
         */
        "babyDeed5" = "babyDeed5";

    
        /**
         * value: "babyDeed6"
         * @const
         */
        "babyDeed6" = "babyDeed6";

    
        /**
         * value: "babyDeed7"
         * @const
         */
        "babyDeed7" = "babyDeed7";

    
        /**
         * value: "babyDeed8"
         * @const
         */
        "babyDeed8" = "babyDeed8";

    
        /**
         * value: "babyDeed9"
         * @const
         */
        "babyDeed9" = "babyDeed9";

    
        /**
         * value: "deathRecord"
         * @const
         */
        "deathRecord" = "deathRecord";

    
        /**
         * value: "privateBusinessDocs"
         * @const
         */
        "privateBusinessDocs" = "privateBusinessDocs";

    
        /**
         * value: "otherDocs"
         * @const
         */
        "otherDocs" = "otherDocs";

    
        /**
         * value: "miscNoticesDocs"
         * @const
         */
        "miscNoticesDocs" = "miscNoticesDocs";

    
        /**
         * value: "landPatent1"
         * @const
         */
        "landPatent1" = "landPatent1";

    
        /**
         * value: "landPatent2"
         * @const
         */
        "landPatent2" = "landPatent2";

    
        /**
         * value: "landPatent3"
         * @const
         */
        "landPatent3" = "landPatent3";

    
        /**
         * value: "landPatent4"
         * @const
         */
        "landPatent4" = "landPatent4";

    
        /**
         * value: "landPatent5"
         * @const
         */
        "landPatent5" = "landPatent5";

    
        /**
         * value: "territorialGovtDocs"
         * @const
         */
        "territorialGovtDocs" = "territorialGovtDocs";

    
        /**
         * value: "municipalGovtDocs"
         * @const
         */
        "municipalGovtDocs" = "municipalGovtDocs";

    
        /**
         * value: "commercialEntityDocs"
         * @const
         */
        "commercialEntityDocs" = "commercialEntityDocs";

    
        /**
         * value: "commonLawWill"
         * @const
         */
        "commonLawWill" = "commonLawWill";

    

    /**
    * Returns a <code>MembershipDocKey</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MembershipDocKey} The enum <code>MembershipDocKey</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

