/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResMembershipDocs from './ResMembershipDocs';

/**
 * The MemberDocsGet200Response model module.
 * @module model/MemberDocsGet200Response
 * @version 0.1.0
 */
class MemberDocsGet200Response {
    /**
     * Constructs a new <code>MemberDocsGet200Response</code>.
     * @alias module:model/MemberDocsGet200Response
     */
    constructor() { 
        
        MemberDocsGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberDocsGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberDocsGet200Response} obj Optional instance to populate.
     * @return {module:model/MemberDocsGet200Response} The populated <code>MemberDocsGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberDocsGet200Response();

            if (data.hasOwnProperty('docs')) {
                obj['docs'] = ResMembershipDocs.constructFromObject(data['docs']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemberDocsGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MemberDocsGet200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `docs`
        if (data['docs']) { // data not null
          ResMembershipDocs.validateJSON(data['docs']);
        }

        return true;
    }


}



/**
 * @member {module:model/ResMembershipDocs} docs
 */
MemberDocsGet200Response.prototype['docs'] = undefined;






export default MemberDocsGet200Response;

