/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberCredentialCardsUpdateOneExpiryRequest model module.
 * @module model/MemberCredentialCardsUpdateOneExpiryRequest
 * @version 0.1.0
 */
class MemberCredentialCardsUpdateOneExpiryRequest {
    /**
     * Constructs a new <code>MemberCredentialCardsUpdateOneExpiryRequest</code>.
     * @alias module:model/MemberCredentialCardsUpdateOneExpiryRequest
     * @param expirationDate {Date} 
     */
    constructor(expirationDate) { 
        
        MemberCredentialCardsUpdateOneExpiryRequest.initialize(this, expirationDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, expirationDate) { 
        obj['expirationDate'] = expirationDate;
    }

    /**
     * Constructs a <code>MemberCredentialCardsUpdateOneExpiryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberCredentialCardsUpdateOneExpiryRequest} obj Optional instance to populate.
     * @return {module:model/MemberCredentialCardsUpdateOneExpiryRequest} The populated <code>MemberCredentialCardsUpdateOneExpiryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberCredentialCardsUpdateOneExpiryRequest();

            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemberCredentialCardsUpdateOneExpiryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MemberCredentialCardsUpdateOneExpiryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MemberCredentialCardsUpdateOneExpiryRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

MemberCredentialCardsUpdateOneExpiryRequest.RequiredProperties = ["expirationDate"];

/**
 * @member {Date} expirationDate
 */
MemberCredentialCardsUpdateOneExpiryRequest.prototype['expirationDate'] = undefined;






export default MemberCredentialCardsUpdateOneExpiryRequest;

