/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResMemberDoc from './ResMemberDoc';

/**
 * The MemberDocsUpdateOne200Response model module.
 * @module model/MemberDocsUpdateOne200Response
 * @version 0.1.0
 */
class MemberDocsUpdateOne200Response {
    /**
     * Constructs a new <code>MemberDocsUpdateOne200Response</code>.
     * @alias module:model/MemberDocsUpdateOne200Response
     */
    constructor() { 
        
        MemberDocsUpdateOne200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberDocsUpdateOne200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberDocsUpdateOne200Response} obj Optional instance to populate.
     * @return {module:model/MemberDocsUpdateOne200Response} The populated <code>MemberDocsUpdateOne200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberDocsUpdateOne200Response();

            if (data.hasOwnProperty('doc')) {
                obj['doc'] = ResMemberDoc.constructFromObject(data['doc']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemberDocsUpdateOne200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MemberDocsUpdateOne200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `doc`
        if (data['doc']) { // data not null
          ResMemberDoc.validateJSON(data['doc']);
        }

        return true;
    }


}



/**
 * @member {module:model/ResMemberDoc} doc
 */
MemberDocsUpdateOne200Response.prototype['doc'] = undefined;






export default MemberDocsUpdateOne200Response;

