/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MemberNationalityStatus from './MemberNationalityStatus';
import MemberRole from './MemberRole';
import MemberStatus from './MemberStatus';

/**
 * The MemberUpdateRequest model module.
 * @module model/MemberUpdateRequest
 * @version 0.1.0
 */
class MemberUpdateRequest {
    /**
     * Constructs a new <code>MemberUpdateRequest</code>.
     * @alias module:model/MemberUpdateRequest
     */
    constructor() { 
        
        MemberUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberUpdateRequest} obj Optional instance to populate.
     * @return {module:model/MemberUpdateRequest} The populated <code>MemberUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberUpdateRequest();

            if (data.hasOwnProperty('role')) {
                obj['role'] = MemberRole.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('recordingSecretaryEmail')) {
                obj['recordingSecretaryEmail'] = ApiClient.convertToType(data['recordingSecretaryEmail'], 'String');
            }
            if (data.hasOwnProperty('coordinatorEmail')) {
                obj['coordinatorEmail'] = ApiClient.convertToType(data['coordinatorEmail'], 'String');
            }
            if (data.hasOwnProperty('memberStatus')) {
                obj['memberStatus'] = MemberStatus.constructFromObject(data['memberStatus']);
            }
            if (data.hasOwnProperty('nationality')) {
                obj['nationality'] = ApiClient.convertToType(data['nationality'], 'String');
            }
            if (data.hasOwnProperty('nationalityStatus')) {
                obj['nationalityStatus'] = MemberNationalityStatus.constructFromObject(data['nationalityStatus']);
            }
            if (data.hasOwnProperty('credentialCardFee')) {
                obj['credentialCardFee'] = ApiClient.convertToType(data['credentialCardFee'], 'String');
            }
            if (data.hasOwnProperty('trainingCourseFee')) {
                obj['trainingCourseFee'] = ApiClient.convertToType(data['trainingCourseFee'], 'String');
            }
            if (data.hasOwnProperty('donationStateAssembly')) {
                obj['donationStateAssembly'] = ApiClient.convertToType(data['donationStateAssembly'], 'String');
            }
            if (data.hasOwnProperty('donationCountyAssembly')) {
                obj['donationCountyAssembly'] = ApiClient.convertToType(data['donationCountyAssembly'], 'String');
            }
            if (data.hasOwnProperty('donationStateChiefMarshal')) {
                obj['donationStateChiefMarshal'] = ApiClient.convertToType(data['donationStateChiefMarshal'], 'String');
            }
            if (data.hasOwnProperty('donationDesignatedRecipient')) {
                obj['donationDesignatedRecipient'] = ApiClient.convertToType(data['donationDesignatedRecipient'], 'String');
            }
            if (data.hasOwnProperty('donationDesignatedAmount')) {
                obj['donationDesignatedAmount'] = ApiClient.convertToType(data['donationDesignatedAmount'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemberUpdateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MemberUpdateRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['recordingSecretaryEmail'] && !(typeof data['recordingSecretaryEmail'] === 'string' || data['recordingSecretaryEmail'] instanceof String)) {
            throw new Error("Expected the field `recordingSecretaryEmail` to be a primitive type in the JSON string but got " + data['recordingSecretaryEmail']);
        }
        // ensure the json data is a string
        if (data['coordinatorEmail'] && !(typeof data['coordinatorEmail'] === 'string' || data['coordinatorEmail'] instanceof String)) {
            throw new Error("Expected the field `coordinatorEmail` to be a primitive type in the JSON string but got " + data['coordinatorEmail']);
        }
        // ensure the json data is a string
        if (data['nationality'] && !(typeof data['nationality'] === 'string' || data['nationality'] instanceof String)) {
            throw new Error("Expected the field `nationality` to be a primitive type in the JSON string but got " + data['nationality']);
        }
        // ensure the json data is a string
        if (data['credentialCardFee'] && !(typeof data['credentialCardFee'] === 'string' || data['credentialCardFee'] instanceof String)) {
            throw new Error("Expected the field `credentialCardFee` to be a primitive type in the JSON string but got " + data['credentialCardFee']);
        }
        // ensure the json data is a string
        if (data['trainingCourseFee'] && !(typeof data['trainingCourseFee'] === 'string' || data['trainingCourseFee'] instanceof String)) {
            throw new Error("Expected the field `trainingCourseFee` to be a primitive type in the JSON string but got " + data['trainingCourseFee']);
        }
        // ensure the json data is a string
        if (data['donationStateAssembly'] && !(typeof data['donationStateAssembly'] === 'string' || data['donationStateAssembly'] instanceof String)) {
            throw new Error("Expected the field `donationStateAssembly` to be a primitive type in the JSON string but got " + data['donationStateAssembly']);
        }
        // ensure the json data is a string
        if (data['donationCountyAssembly'] && !(typeof data['donationCountyAssembly'] === 'string' || data['donationCountyAssembly'] instanceof String)) {
            throw new Error("Expected the field `donationCountyAssembly` to be a primitive type in the JSON string but got " + data['donationCountyAssembly']);
        }
        // ensure the json data is a string
        if (data['donationStateChiefMarshal'] && !(typeof data['donationStateChiefMarshal'] === 'string' || data['donationStateChiefMarshal'] instanceof String)) {
            throw new Error("Expected the field `donationStateChiefMarshal` to be a primitive type in the JSON string but got " + data['donationStateChiefMarshal']);
        }
        // ensure the json data is a string
        if (data['donationDesignatedRecipient'] && !(typeof data['donationDesignatedRecipient'] === 'string' || data['donationDesignatedRecipient'] instanceof String)) {
            throw new Error("Expected the field `donationDesignatedRecipient` to be a primitive type in the JSON string but got " + data['donationDesignatedRecipient']);
        }
        // ensure the json data is a string
        if (data['donationDesignatedAmount'] && !(typeof data['donationDesignatedAmount'] === 'string' || data['donationDesignatedAmount'] instanceof String)) {
            throw new Error("Expected the field `donationDesignatedAmount` to be a primitive type in the JSON string but got " + data['donationDesignatedAmount']);
        }

        return true;
    }


}



/**
 * @member {module:model/MemberRole} role
 */
MemberUpdateRequest.prototype['role'] = undefined;

/**
 * @member {String} recordingSecretaryEmail
 */
MemberUpdateRequest.prototype['recordingSecretaryEmail'] = undefined;

/**
 * @member {String} coordinatorEmail
 */
MemberUpdateRequest.prototype['coordinatorEmail'] = undefined;

/**
 * @member {module:model/MemberStatus} memberStatus
 */
MemberUpdateRequest.prototype['memberStatus'] = undefined;

/**
 * @member {String} nationality
 */
MemberUpdateRequest.prototype['nationality'] = undefined;

/**
 * @member {module:model/MemberNationalityStatus} nationalityStatus
 */
MemberUpdateRequest.prototype['nationalityStatus'] = undefined;

/**
 * @member {String} credentialCardFee
 */
MemberUpdateRequest.prototype['credentialCardFee'] = undefined;

/**
 * @member {String} trainingCourseFee
 */
MemberUpdateRequest.prototype['trainingCourseFee'] = undefined;

/**
 * @member {String} donationStateAssembly
 */
MemberUpdateRequest.prototype['donationStateAssembly'] = undefined;

/**
 * @member {String} donationCountyAssembly
 */
MemberUpdateRequest.prototype['donationCountyAssembly'] = undefined;

/**
 * @member {String} donationStateChiefMarshal
 */
MemberUpdateRequest.prototype['donationStateChiefMarshal'] = undefined;

/**
 * @member {String} donationDesignatedRecipient
 */
MemberUpdateRequest.prototype['donationDesignatedRecipient'] = undefined;

/**
 * @member {String} donationDesignatedAmount
 */
MemberUpdateRequest.prototype['donationDesignatedAmount'] = undefined;






export default MemberUpdateRequest;

