/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MemberGender} from './MemberGender';
import {MemberProfileCounty} from './MemberProfileCounty';

/**
 * The MembershipsSignupBody model module.
 * @module model/MembershipsSignupBody
 * @version 0.1.0
 */
export class MembershipsSignupBody {
  /**
   * Constructs a new <code>MembershipsSignupBody</code>.
   * @alias module:model/MembershipsSignupBody
   * @class
   * @param captchaResToken {String} 
   * @param email {String} 
   * @param password {String} 
   * @param passwordConf {String} 
   * @param recordingSecretaryEmail {String} 
   * @param coordinatorEmail {String} 
   * @param firstName {String} 
   * @param lastName {String} 
   * @param gender {module:model/MemberGender} 
   * @param dob {Date} 
   * @param addrLine1 {String} 
   * @param addrCity {String} 
   * @param addrState {String} 
   * @param addrZip {String} 
   * @param addrCounty {module:model/MemberProfileCounty} 
   * @param phone {String} 
   */
  constructor(captchaResToken, email, password, passwordConf, recordingSecretaryEmail, coordinatorEmail, firstName, lastName, gender, dob, addrLine1, addrCity, addrState, addrZip, addrCounty, phone) {
    this.captchaResToken = captchaResToken;
    this.email = email;
    this.password = password;
    this.passwordConf = passwordConf;
    this.recordingSecretaryEmail = recordingSecretaryEmail;
    this.coordinatorEmail = coordinatorEmail;
    this.firstName = firstName;
    this.lastName = lastName;
    this.gender = gender;
    this.dob = dob;
    this.addrLine1 = addrLine1;
    this.addrCity = addrCity;
    this.addrState = addrState;
    this.addrZip = addrZip;
    this.addrCounty = addrCounty;
    this.phone = phone;
  }

  /**
   * Constructs a <code>MembershipsSignupBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MembershipsSignupBody} obj Optional instance to populate.
   * @return {module:model/MembershipsSignupBody} The populated <code>MembershipsSignupBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MembershipsSignupBody();
      if (data.hasOwnProperty('captchaResToken'))
        obj.captchaResToken = ApiClient.convertToType(data['captchaResToken'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('passwordConf'))
        obj.passwordConf = ApiClient.convertToType(data['passwordConf'], 'String');
      if (data.hasOwnProperty('recordingSecretaryEmail'))
        obj.recordingSecretaryEmail = ApiClient.convertToType(data['recordingSecretaryEmail'], 'String');
      if (data.hasOwnProperty('coordinatorEmail'))
        obj.coordinatorEmail = ApiClient.convertToType(data['coordinatorEmail'], 'String');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('middleName'))
        obj.middleName = ApiClient.convertToType(data['middleName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = MemberGender.constructFromObject(data['gender']);
      if (data.hasOwnProperty('dob'))
        obj.dob = ApiClient.convertToType(data['dob'], 'Date');
      if (data.hasOwnProperty('addrLine1'))
        obj.addrLine1 = ApiClient.convertToType(data['addrLine1'], 'String');
      if (data.hasOwnProperty('addrLine2'))
        obj.addrLine2 = ApiClient.convertToType(data['addrLine2'], 'String');
      if (data.hasOwnProperty('addrCity'))
        obj.addrCity = ApiClient.convertToType(data['addrCity'], 'String');
      if (data.hasOwnProperty('addrState'))
        obj.addrState = ApiClient.convertToType(data['addrState'], 'String');
      if (data.hasOwnProperty('addrZip'))
        obj.addrZip = ApiClient.convertToType(data['addrZip'], 'String');
      if (data.hasOwnProperty('addrCounty'))
        obj.addrCounty = MemberProfileCounty.constructFromObject(data['addrCounty']);
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('emailAlt'))
        obj.emailAlt = ApiClient.convertToType(data['emailAlt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} captchaResToken
 */
MembershipsSignupBody.prototype.captchaResToken = undefined;

/**
 * @member {String} email
 */
MembershipsSignupBody.prototype.email = undefined;

/**
 * @member {String} password
 */
MembershipsSignupBody.prototype.password = undefined;

/**
 * @member {String} passwordConf
 */
MembershipsSignupBody.prototype.passwordConf = undefined;

/**
 * @member {String} recordingSecretaryEmail
 */
MembershipsSignupBody.prototype.recordingSecretaryEmail = undefined;

/**
 * @member {String} coordinatorEmail
 */
MembershipsSignupBody.prototype.coordinatorEmail = undefined;

/**
 * @member {String} firstName
 */
MembershipsSignupBody.prototype.firstName = undefined;

/**
 * @member {String} middleName
 */
MembershipsSignupBody.prototype.middleName = undefined;

/**
 * @member {String} lastName
 */
MembershipsSignupBody.prototype.lastName = undefined;

/**
 * @member {module:model/MemberGender} gender
 */
MembershipsSignupBody.prototype.gender = undefined;

/**
 * @member {Date} dob
 */
MembershipsSignupBody.prototype.dob = undefined;

/**
 * @member {String} addrLine1
 */
MembershipsSignupBody.prototype.addrLine1 = undefined;

/**
 * @member {String} addrLine2
 */
MembershipsSignupBody.prototype.addrLine2 = undefined;

/**
 * @member {String} addrCity
 */
MembershipsSignupBody.prototype.addrCity = undefined;

/**
 * @member {String} addrState
 */
MembershipsSignupBody.prototype.addrState = undefined;

/**
 * @member {String} addrZip
 */
MembershipsSignupBody.prototype.addrZip = undefined;

/**
 * @member {module:model/MemberProfileCounty} addrCounty
 */
MembershipsSignupBody.prototype.addrCounty = undefined;

/**
 * @member {String} phone
 */
MembershipsSignupBody.prototype.phone = undefined;

/**
 * @member {String} emailAlt
 */
MembershipsSignupBody.prototype.emailAlt = undefined;

