/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResShopOrderPayment from './ResShopOrderPayment';

/**
 * The MemberOrderPaymentList200Response model module.
 * @module model/MemberOrderPaymentList200Response
 * @version 0.1.0
 */
class MemberOrderPaymentList200Response {
    /**
     * Constructs a new <code>MemberOrderPaymentList200Response</code>.
     * @alias module:model/MemberOrderPaymentList200Response
     */
    constructor() { 
        
        MemberOrderPaymentList200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberOrderPaymentList200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberOrderPaymentList200Response} obj Optional instance to populate.
     * @return {module:model/MemberOrderPaymentList200Response} The populated <code>MemberOrderPaymentList200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberOrderPaymentList200Response();

            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], [ResShopOrderPayment]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemberOrderPaymentList200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MemberOrderPaymentList200Response</code>.
     */
    static validateJSON(data) {
        if (data['order']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['order'])) {
                throw new Error("Expected the field `order` to be an array in the JSON data but got " + data['order']);
            }
            // validate the optional field `order` (array)
            for (const item of data['order']) {
                ResShopOrderPayment.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ResShopOrderPayment>} order
 */
MemberOrderPaymentList200Response.prototype['order'] = undefined;






export default MemberOrderPaymentList200Response;

