/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MemberIdCredentialCardsBody model module.
 * @module model/MemberIdCredentialCardsBody
 * @version 0.1.0
 */
export class MemberIdCredentialCardsBody {
  /**
   * Constructs a new <code>MemberIdCredentialCardsBody</code>.
   * @alias module:model/MemberIdCredentialCardsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MemberIdCredentialCardsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MemberIdCredentialCardsBody} obj Optional instance to populate.
   * @return {module:model/MemberIdCredentialCardsBody} The populated <code>MemberIdCredentialCardsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MemberIdCredentialCardsBody();
      if (data.hasOwnProperty('purchaseItemId'))
        obj.purchaseItemId = ApiClient.convertToType(data['purchaseItemId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} purchaseItemId
 */
MemberIdCredentialCardsBody.prototype.purchaseItemId = undefined;

