/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberOrdersUpdateOneRequest model module.
 * @module model/MemberOrdersUpdateOneRequest
 * @version 0.1.0
 */
class MemberOrdersUpdateOneRequest {
    /**
     * Constructs a new <code>MemberOrdersUpdateOneRequest</code>.
     * @alias module:model/MemberOrdersUpdateOneRequest
     */
    constructor() { 
        
        MemberOrdersUpdateOneRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MemberOrdersUpdateOneRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MemberOrdersUpdateOneRequest} obj Optional instance to populate.
     * @return {module:model/MemberOrdersUpdateOneRequest} The populated <code>MemberOrdersUpdateOneRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MemberOrdersUpdateOneRequest();

            if (data.hasOwnProperty('credit')) {
                obj['credit'] = ApiClient.convertToType(data['credit'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MemberOrdersUpdateOneRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MemberOrdersUpdateOneRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['credit'] && !(typeof data['credit'] === 'string' || data['credit'] instanceof String)) {
            throw new Error("Expected the field `credit` to be a primitive type in the JSON string but got " + data['credit']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }

        return true;
    }


}



/**
 * @member {String} credit
 */
MemberOrdersUpdateOneRequest.prototype['credit'] = undefined;

/**
 * @member {String} notes
 */
MemberOrdersUpdateOneRequest.prototype['notes'] = undefined;






export default MemberOrdersUpdateOneRequest;

