/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MemberGender} from './MemberGender';
import {MemberInterestsCommittee} from './MemberInterestsCommittee';
import {MemberInterestsIndividual} from './MemberInterestsIndividual';
import {MemberProfileCounty} from './MemberProfileCounty';

/**
 * The MemberIdProfileBody model module.
 * @module model/MemberIdProfileBody
 * @version 0.1.0
 */
export class MemberIdProfileBody {
  /**
   * Constructs a new <code>MemberIdProfileBody</code>.
   * @alias module:model/MemberIdProfileBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MemberIdProfileBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MemberIdProfileBody} obj Optional instance to populate.
   * @return {module:model/MemberIdProfileBody} The populated <code>MemberIdProfileBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MemberIdProfileBody();
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('middleName'))
        obj.middleName = ApiClient.convertToType(data['middleName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = MemberGender.constructFromObject(data['gender']);
      if (data.hasOwnProperty('dob'))
        obj.dob = ApiClient.convertToType(data['dob'], 'Date');
      if (data.hasOwnProperty('deceasedDate'))
        obj.deceasedDate = ApiClient.convertToType(data['deceasedDate'], 'Date');
      if (data.hasOwnProperty('addrLine1'))
        obj.addrLine1 = ApiClient.convertToType(data['addrLine1'], 'String');
      if (data.hasOwnProperty('addrLine2'))
        obj.addrLine2 = ApiClient.convertToType(data['addrLine2'], 'String');
      if (data.hasOwnProperty('addrCity'))
        obj.addrCity = ApiClient.convertToType(data['addrCity'], 'String');
      if (data.hasOwnProperty('addrState'))
        obj.addrState = ApiClient.convertToType(data['addrState'], 'String');
      if (data.hasOwnProperty('addrZip'))
        obj.addrZip = ApiClient.convertToType(data['addrZip'], 'String');
      if (data.hasOwnProperty('addrCounty'))
        obj.addrCounty = MemberProfileCounty.constructFromObject(data['addrCounty']);
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('emailAlt'))
        obj.emailAlt = ApiClient.convertToType(data['emailAlt'], 'String');
      if (data.hasOwnProperty('isListedDirectory'))
        obj.isListedDirectory = ApiClient.convertToType(data['isListedDirectory'], 'Boolean');
      if (data.hasOwnProperty('isDesignationAmish'))
        obj.isDesignationAmish = ApiClient.convertToType(data['isDesignationAmish'], 'Boolean');
      if (data.hasOwnProperty('proLicense'))
        obj.proLicense = ApiClient.convertToType(data['proLicense'], 'String');
      if (data.hasOwnProperty('companyName'))
        obj.companyName = ApiClient.convertToType(data['companyName'], 'String');
      if (data.hasOwnProperty('interestsCommittee'))
        obj.interestsCommittee = ApiClient.convertToType(data['interestsCommittee'], [MemberInterestsCommittee]);
      if (data.hasOwnProperty('interestsIndividual'))
        obj.interestsIndividual = ApiClient.convertToType(data['interestsIndividual'], [MemberInterestsIndividual]);
      if (data.hasOwnProperty('interestsIndividualOther'))
        obj.interestsIndividualOther = ApiClient.convertToType(data['interestsIndividualOther'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} firstName
 */
MemberIdProfileBody.prototype.firstName = undefined;

/**
 * @member {String} middleName
 */
MemberIdProfileBody.prototype.middleName = undefined;

/**
 * @member {String} lastName
 */
MemberIdProfileBody.prototype.lastName = undefined;

/**
 * @member {module:model/MemberGender} gender
 */
MemberIdProfileBody.prototype.gender = undefined;

/**
 * @member {Date} dob
 */
MemberIdProfileBody.prototype.dob = undefined;

/**
 * @member {Date} deceasedDate
 */
MemberIdProfileBody.prototype.deceasedDate = undefined;

/**
 * @member {String} addrLine1
 */
MemberIdProfileBody.prototype.addrLine1 = undefined;

/**
 * @member {String} addrLine2
 */
MemberIdProfileBody.prototype.addrLine2 = undefined;

/**
 * @member {String} addrCity
 */
MemberIdProfileBody.prototype.addrCity = undefined;

/**
 * @member {String} addrState
 */
MemberIdProfileBody.prototype.addrState = undefined;

/**
 * @member {String} addrZip
 */
MemberIdProfileBody.prototype.addrZip = undefined;

/**
 * @member {module:model/MemberProfileCounty} addrCounty
 */
MemberIdProfileBody.prototype.addrCounty = undefined;

/**
 * @member {String} phone
 */
MemberIdProfileBody.prototype.phone = undefined;

/**
 * @member {String} emailAlt
 */
MemberIdProfileBody.prototype.emailAlt = undefined;

/**
 * @member {Boolean} isListedDirectory
 */
MemberIdProfileBody.prototype.isListedDirectory = undefined;

/**
 * @member {Boolean} isDesignationAmish
 */
MemberIdProfileBody.prototype.isDesignationAmish = undefined;

/**
 * @member {String} proLicense
 */
MemberIdProfileBody.prototype.proLicense = undefined;

/**
 * @member {String} companyName
 */
MemberIdProfileBody.prototype.companyName = undefined;

/**
 * @member {Array.<module:model/MemberInterestsCommittee>} interestsCommittee
 */
MemberIdProfileBody.prototype.interestsCommittee = undefined;

/**
 * @member {Array.<module:model/MemberInterestsIndividual>} interestsIndividual
 */
MemberIdProfileBody.prototype.interestsIndividual = undefined;

/**
 * @member {String} interestsIndividualOther
 */
MemberIdProfileBody.prototype.interestsIndividualOther = undefined;

