/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProfileDocKeyNameBody model module.
 * @module model/ProfileDocKeyNameBody
 * @version 0.1.0
 */
export class ProfileDocKeyNameBody {
  /**
   * Constructs a new <code>ProfileDocKeyNameBody</code>.
   * @alias module:model/ProfileDocKeyNameBody
   * @class
   * @param docName {String} 
   */
  constructor(docName) {
    this.docName = docName;
  }

  /**
   * Constructs a <code>ProfileDocKeyNameBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfileDocKeyNameBody} obj Optional instance to populate.
   * @return {module:model/ProfileDocKeyNameBody} The populated <code>ProfileDocKeyNameBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProfileDocKeyNameBody();
      if (data.hasOwnProperty('docName'))
        obj.docName = ApiClient.convertToType(data['docName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} docName
 */
ProfileDocKeyNameBody.prototype.docName = undefined;

