/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthRole from './AuthRole';

/**
 * The ResAccount model module.
 * @module model/ResAccount
 * @version 0.1.0
 */
class ResAccount {
    /**
     * Constructs a new <code>ResAccount</code>.
     * @alias module:model/ResAccount
     */
    constructor() { 
        
        ResAccount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResAccount} obj Optional instance to populate.
     * @return {module:model/ResAccount} The populated <code>ResAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResAccount();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], Object);
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], Object);
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = AuthRole.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('isChangePassword')) {
                obj['isChangePassword'] = ApiClient.convertToType(data['isChangePassword'], 'Boolean');
            }
            if (data.hasOwnProperty('isBlocked')) {
                obj['isBlocked'] = ApiClient.convertToType(data['isBlocked'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], Object);
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], Object);
            }
            if (data.hasOwnProperty('deletedAt')) {
                obj['deletedAt'] = ApiClient.convertToType(data['deletedAt'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResAccount</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResAccount</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} id
 */
ResAccount.prototype['id'] = undefined;

/**
 * @member {Object} email
 */
ResAccount.prototype['email'] = undefined;

/**
 * @member {module:model/AuthRole} role
 */
ResAccount.prototype['role'] = undefined;

/**
 * @member {Boolean} isChangePassword
 */
ResAccount.prototype['isChangePassword'] = undefined;

/**
 * @member {Boolean} isBlocked
 */
ResAccount.prototype['isBlocked'] = undefined;

/**
 * @member {Object} createdAt
 */
ResAccount.prototype['createdAt'] = undefined;

/**
 * @member {Object} updatedAt
 */
ResAccount.prototype['updatedAt'] = undefined;

/**
 * @member {Object} deletedAt
 */
ResAccount.prototype['deletedAt'] = undefined;






export default ResAccount;

