/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResMemberDoc from './ResMemberDoc';

/**
 * The ResMemberProfileDocs model module.
 * @module model/ResMemberProfileDocs
 * @version 0.1.0
 */
class ResMemberProfileDocs {
    /**
     * Constructs a new <code>ResMemberProfileDocs</code>.
     * @alias module:model/ResMemberProfileDocs
     */
    constructor() { 
        
        ResMemberProfileDocs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResMemberProfileDocs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResMemberProfileDocs} obj Optional instance to populate.
     * @return {module:model/ResMemberProfileDocs} The populated <code>ResMemberProfileDocs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResMemberProfileDocs();

            if (data.hasOwnProperty('imagePhoto')) {
                obj['imagePhoto'] = ResMemberDoc.constructFromObject(data['imagePhoto']);
            }
            if (data.hasOwnProperty('imageSeal')) {
                obj['imageSeal'] = ResMemberDoc.constructFromObject(data['imageSeal']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResMemberProfileDocs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResMemberProfileDocs</code>.
     */
    static validateJSON(data) {
        // validate the optional field `imagePhoto`
        if (data['imagePhoto']) { // data not null
          ResMemberDoc.validateJSON(data['imagePhoto']);
        }
        // validate the optional field `imageSeal`
        if (data['imageSeal']) { // data not null
          ResMemberDoc.validateJSON(data['imageSeal']);
        }

        return true;
    }


}



/**
 * @member {module:model/ResMemberDoc} imagePhoto
 */
ResMemberProfileDocs.prototype['imagePhoto'] = undefined;

/**
 * @member {module:model/ResMemberDoc} imageSeal
 */
ResMemberProfileDocs.prototype['imageSeal'] = undefined;






export default ResMemberProfileDocs;

