/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DirectoryListing from './DirectoryListing';
import MemberRole from './MemberRole';
import ResMemberBase from './ResMemberBase';
import ResMemberBaseNationality from './ResMemberBaseNationality';
import ResMemberFeesDonations from './ResMemberFeesDonations';
import ResMemberProfile from './ResMemberProfile';

/**
 * The ResMember model module.
 * @module model/ResMember
 * @version 0.1.0
 */
class ResMember {
    /**
     * Constructs a new <code>ResMember</code>.
     * @alias module:model/ResMember
     * @implements module:model/ResMemberBase
     * @implements module:model/ResMemberFeesDonations
     */
    constructor() { 
        ResMemberBase.initialize(this);ResMemberFeesDonations.initialize(this);
        ResMember.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResMember</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResMember} obj Optional instance to populate.
     * @return {module:model/ResMember} The populated <code>ResMember</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResMember();
            ResMemberBase.constructFromObject(data, obj);
            ResMemberFeesDonations.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = MemberRole.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('coordinator')) {
                obj['coordinator'] = DirectoryListing.constructFromObject(data['coordinator']);
            }
            if (data.hasOwnProperty('recordingSecretary')) {
                obj['recordingSecretary'] = DirectoryListing.constructFromObject(data['recordingSecretary']);
            }
            if (data.hasOwnProperty('nationality')) {
                obj['nationality'] = ResMemberBaseNationality.constructFromObject(data['nationality']);
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ResMemberProfile.constructFromObject(data['profile']);
            }
            if (data.hasOwnProperty('credentialCardFee')) {
                obj['credentialCardFee'] = ApiClient.convertToType(data['credentialCardFee'], 'String');
            }
            if (data.hasOwnProperty('trainingCourseFee')) {
                obj['trainingCourseFee'] = ApiClient.convertToType(data['trainingCourseFee'], 'String');
            }
            if (data.hasOwnProperty('donationStateAssembly')) {
                obj['donationStateAssembly'] = ApiClient.convertToType(data['donationStateAssembly'], 'String');
            }
            if (data.hasOwnProperty('donationCountyAssembly')) {
                obj['donationCountyAssembly'] = ApiClient.convertToType(data['donationCountyAssembly'], 'String');
            }
            if (data.hasOwnProperty('donationStateChiefMarshal')) {
                obj['donationStateChiefMarshal'] = ApiClient.convertToType(data['donationStateChiefMarshal'], 'String');
            }
            if (data.hasOwnProperty('donationDesignatedRecipient')) {
                obj['donationDesignatedRecipient'] = ApiClient.convertToType(data['donationDesignatedRecipient'], 'String');
            }
            if (data.hasOwnProperty('donationDesignatedAmount')) {
                obj['donationDesignatedAmount'] = ApiClient.convertToType(data['donationDesignatedAmount'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResMember</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResMember</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // validate the optional field `coordinator`
        if (data['coordinator']) { // data not null
          DirectoryListing.validateJSON(data['coordinator']);
        }
        // validate the optional field `recordingSecretary`
        if (data['recordingSecretary']) { // data not null
          DirectoryListing.validateJSON(data['recordingSecretary']);
        }
        // validate the optional field `nationality`
        if (data['nationality']) { // data not null
          ResMemberBaseNationality.validateJSON(data['nationality']);
        }
        // validate the optional field `profile`
        if (data['profile']) { // data not null
          ResMemberProfile.validateJSON(data['profile']);
        }
        // ensure the json data is a string
        if (data['credentialCardFee'] && !(typeof data['credentialCardFee'] === 'string' || data['credentialCardFee'] instanceof String)) {
            throw new Error("Expected the field `credentialCardFee` to be a primitive type in the JSON string but got " + data['credentialCardFee']);
        }
        // ensure the json data is a string
        if (data['trainingCourseFee'] && !(typeof data['trainingCourseFee'] === 'string' || data['trainingCourseFee'] instanceof String)) {
            throw new Error("Expected the field `trainingCourseFee` to be a primitive type in the JSON string but got " + data['trainingCourseFee']);
        }
        // ensure the json data is a string
        if (data['donationStateAssembly'] && !(typeof data['donationStateAssembly'] === 'string' || data['donationStateAssembly'] instanceof String)) {
            throw new Error("Expected the field `donationStateAssembly` to be a primitive type in the JSON string but got " + data['donationStateAssembly']);
        }
        // ensure the json data is a string
        if (data['donationCountyAssembly'] && !(typeof data['donationCountyAssembly'] === 'string' || data['donationCountyAssembly'] instanceof String)) {
            throw new Error("Expected the field `donationCountyAssembly` to be a primitive type in the JSON string but got " + data['donationCountyAssembly']);
        }
        // ensure the json data is a string
        if (data['donationStateChiefMarshal'] && !(typeof data['donationStateChiefMarshal'] === 'string' || data['donationStateChiefMarshal'] instanceof String)) {
            throw new Error("Expected the field `donationStateChiefMarshal` to be a primitive type in the JSON string but got " + data['donationStateChiefMarshal']);
        }
        // ensure the json data is a string
        if (data['donationDesignatedRecipient'] && !(typeof data['donationDesignatedRecipient'] === 'string' || data['donationDesignatedRecipient'] instanceof String)) {
            throw new Error("Expected the field `donationDesignatedRecipient` to be a primitive type in the JSON string but got " + data['donationDesignatedRecipient']);
        }
        // ensure the json data is a string
        if (data['donationDesignatedAmount'] && !(typeof data['donationDesignatedAmount'] === 'string' || data['donationDesignatedAmount'] instanceof String)) {
            throw new Error("Expected the field `donationDesignatedAmount` to be a primitive type in the JSON string but got " + data['donationDesignatedAmount']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ResMember.prototype['id'] = undefined;

/**
 * @member {String} email
 */
ResMember.prototype['email'] = undefined;

/**
 * @member {module:model/MemberRole} role
 */
ResMember.prototype['role'] = undefined;

/**
 * @member {module:model/DirectoryListing} coordinator
 */
ResMember.prototype['coordinator'] = undefined;

/**
 * @member {module:model/DirectoryListing} recordingSecretary
 */
ResMember.prototype['recordingSecretary'] = undefined;

/**
 * @member {module:model/ResMemberBaseNationality} nationality
 */
ResMember.prototype['nationality'] = undefined;

/**
 * @member {module:model/ResMemberProfile} profile
 */
ResMember.prototype['profile'] = undefined;

/**
 * @member {String} credentialCardFee
 */
ResMember.prototype['credentialCardFee'] = undefined;

/**
 * @member {String} trainingCourseFee
 */
ResMember.prototype['trainingCourseFee'] = undefined;

/**
 * @member {String} donationStateAssembly
 */
ResMember.prototype['donationStateAssembly'] = undefined;

/**
 * @member {String} donationCountyAssembly
 */
ResMember.prototype['donationCountyAssembly'] = undefined;

/**
 * @member {String} donationStateChiefMarshal
 */
ResMember.prototype['donationStateChiefMarshal'] = undefined;

/**
 * @member {String} donationDesignatedRecipient
 */
ResMember.prototype['donationDesignatedRecipient'] = undefined;

/**
 * @member {String} donationDesignatedAmount
 */
ResMember.prototype['donationDesignatedAmount'] = undefined;


// Implement ResMemberBase interface:
/**
 * @member {String} id
 */
ResMemberBase.prototype['id'] = undefined;
/**
 * @member {String} email
 */
ResMemberBase.prototype['email'] = undefined;
/**
 * @member {module:model/MemberRole} role
 */
ResMemberBase.prototype['role'] = undefined;
/**
 * @member {module:model/DirectoryListing} coordinator
 */
ResMemberBase.prototype['coordinator'] = undefined;
/**
 * @member {module:model/DirectoryListing} recordingSecretary
 */
ResMemberBase.prototype['recordingSecretary'] = undefined;
/**
 * @member {module:model/ResMemberBaseNationality} nationality
 */
ResMemberBase.prototype['nationality'] = undefined;
/**
 * @member {module:model/ResMemberProfile} profile
 */
ResMemberBase.prototype['profile'] = undefined;
// Implement ResMemberFeesDonations interface:
/**
 * @member {String} credentialCardFee
 */
ResMemberFeesDonations.prototype['credentialCardFee'] = undefined;
/**
 * @member {String} trainingCourseFee
 */
ResMemberFeesDonations.prototype['trainingCourseFee'] = undefined;
/**
 * @member {String} donationStateAssembly
 */
ResMemberFeesDonations.prototype['donationStateAssembly'] = undefined;
/**
 * @member {String} donationCountyAssembly
 */
ResMemberFeesDonations.prototype['donationCountyAssembly'] = undefined;
/**
 * @member {String} donationStateChiefMarshal
 */
ResMemberFeesDonations.prototype['donationStateChiefMarshal'] = undefined;
/**
 * @member {String} donationDesignatedRecipient
 */
ResMemberFeesDonations.prototype['donationDesignatedRecipient'] = undefined;
/**
 * @member {String} donationDesignatedAmount
 */
ResMemberFeesDonations.prototype['donationDesignatedAmount'] = undefined;




export default ResMember;

