/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResMemberDoc model module.
 * @module model/ResMemberDoc
 * @version 0.1.0
 */
export class ResMemberDoc {
  /**
   * Constructs a new <code>ResMemberDoc</code>.
   * @alias module:model/ResMemberDoc
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResMemberDoc</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResMemberDoc} obj Optional instance to populate.
   * @return {module:model/ResMemberDoc} The populated <code>ResMemberDoc</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResMemberDoc();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('ownerId'))
        obj.ownerId = ApiClient.convertToType(data['ownerId'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('signedUrl'))
        obj.signedUrl = ApiClient.convertToType(data['signedUrl'], 'String');
      if (data.hasOwnProperty('sizeMb'))
        obj.sizeMb = ApiClient.convertToType(data['sizeMb'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ResMemberDoc.prototype.id = undefined;

/**
 * @member {String} ownerId
 */
ResMemberDoc.prototype.ownerId = undefined;

/**
 * @member {String} name
 */
ResMemberDoc.prototype.name = undefined;

/**
 * @member {String} signedUrl
 */
ResMemberDoc.prototype.signedUrl = undefined;

/**
 * @member {String} sizeMb
 */
ResMemberDoc.prototype.sizeMb = undefined;

