/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MemberNationalityStatus} from './MemberNationalityStatus';

/**
 * The ResMemberBaseNationality model module.
 * @module model/ResMemberBaseNationality
 * @version 0.1.0
 */
export class ResMemberBaseNationality {
  /**
   * Constructs a new <code>ResMemberBaseNationality</code>.
   * @alias module:model/ResMemberBaseNationality
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResMemberBaseNationality</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResMemberBaseNationality} obj Optional instance to populate.
   * @return {module:model/ResMemberBaseNationality} The populated <code>ResMemberBaseNationality</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResMemberBaseNationality();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = MemberNationalityStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {String} value
 */
ResMemberBaseNationality.prototype.value = undefined;

/**
 * @member {module:model/MemberNationalityStatus} status
 */
ResMemberBaseNationality.prototype.status = undefined;

