/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ResShopItem} from './ResShopItem';

/**
 * The ResShopOrderItem model module.
 * @module model/ResShopOrderItem
 * @version 0.1.0
 */
export class ResShopOrderItem {
  /**
   * Constructs a new <code>ResShopOrderItem</code>.
   * @alias module:model/ResShopOrderItem
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResShopOrderItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResShopOrderItem} obj Optional instance to populate.
   * @return {module:model/ResShopOrderItem} The populated <code>ResShopOrderItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResShopOrderItem();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('amountDiscount'))
        obj.amountDiscount = ApiClient.convertToType(data['amountDiscount'], 'String');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
      if (data.hasOwnProperty('listing'))
        obj.listing = ResShopItem.constructFromObject(data['listing']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ResShopOrderItem.prototype.id = undefined;

/**
 * @member {Number} quantity
 */
ResShopOrderItem.prototype.quantity = undefined;

/**
 * @member {String} amountDiscount
 */
ResShopOrderItem.prototype.amountDiscount = undefined;

/**
 * @member {String} notes
 */
ResShopOrderItem.prototype.notes = undefined;

/**
 * @member {module:model/ResShopItem} listing
 */
ResShopOrderItem.prototype.listing = undefined;

