/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResShopItem from './ResShopItem';

/**
 * The ResShopOrderItem model module.
 * @module model/ResShopOrderItem
 * @version 0.1.0
 */
class ResShopOrderItem {
    /**
     * Constructs a new <code>ResShopOrderItem</code>.
     * @alias module:model/ResShopOrderItem
     */
    constructor() { 
        
        ResShopOrderItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResShopOrderItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResShopOrderItem} obj Optional instance to populate.
     * @return {module:model/ResShopOrderItem} The populated <code>ResShopOrderItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResShopOrderItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('amountDiscount')) {
                obj['amountDiscount'] = ApiClient.convertToType(data['amountDiscount'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('listing')) {
                obj['listing'] = ResShopItem.constructFromObject(data['listing']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResShopOrderItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResShopOrderItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['amountDiscount'] && !(typeof data['amountDiscount'] === 'string' || data['amountDiscount'] instanceof String)) {
            throw new Error("Expected the field `amountDiscount` to be a primitive type in the JSON string but got " + data['amountDiscount']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }
        // validate the optional field `listing`
        if (data['listing']) { // data not null
          ResShopItem.validateJSON(data['listing']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ResShopOrderItem.prototype['id'] = undefined;

/**
 * @member {Number} quantity
 */
ResShopOrderItem.prototype['quantity'] = undefined;

/**
 * @member {String} amountDiscount
 */
ResShopOrderItem.prototype['amountDiscount'] = undefined;

/**
 * @member {String} notes
 */
ResShopOrderItem.prototype['notes'] = undefined;

/**
 * @member {module:model/ResShopItem} listing
 */
ResShopOrderItem.prototype['listing'] = undefined;






export default ResShopOrderItem;

