/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResShopOrderTotals model module.
 * @module model/ResShopOrderTotals
 * @version 0.1.0
 */
export class ResShopOrderTotals {
  /**
   * Constructs a new <code>ResShopOrderTotals</code>.
   * @alias module:model/ResShopOrderTotals
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResShopOrderTotals</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResShopOrderTotals} obj Optional instance to populate.
   * @return {module:model/ResShopOrderTotals} The populated <code>ResShopOrderTotals</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResShopOrderTotals();
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], 'String');
      if (data.hasOwnProperty('credits'))
        obj.credits = ApiClient.convertToType(data['credits'], 'String');
      if (data.hasOwnProperty('net'))
        obj.net = ApiClient.convertToType(data['net'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} items
 */
ResShopOrderTotals.prototype.items = undefined;

/**
 * @member {String} credits
 */
ResShopOrderTotals.prototype.credits = undefined;

/**
 * @member {String} net
 */
ResShopOrderTotals.prototype.net = undefined;

