/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class ShopOrderStatus.
 * @enum {String}
 * @readonly
 */
const ShopOrderStatus = {
  /**
   * value: "OPEN"
   * @const
   */
  OPEN: "OPEN",

  /**
   * value: "CLOSED"
   * @const
   */
  CLOSED: "CLOSED",

  /**
   * value: "SUBMITTED"
   * @const
   */
  SUBMITTED: "SUBMITTED",

  /**
   * value: "PAID"
   * @const
   */
  PAID: "PAID",

  /**
   * value: "CANCELLED"
   * @const
   */
  CANCELLED: "CANCELLED",

  /**
   * value: "CONFIRMED"
   * @const
   */
  CONFIRMED: "CONFIRMED",

  /**
   * Returns a <code>ShopOrderStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ShopOrderStatus} The enum <code>ShopOrderStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ShopOrderStatus};