/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResShopItem from './ResShopItem';

/**
 * The ShopItemsList200Response model module.
 * @module model/ShopItemsList200Response
 * @version 0.1.0
 */
class ShopItemsList200Response {
    /**
     * Constructs a new <code>ShopItemsList200Response</code>.
     * @alias module:model/ShopItemsList200Response
     */
    constructor() { 
        
        ShopItemsList200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShopItemsList200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShopItemsList200Response} obj Optional instance to populate.
     * @return {module:model/ShopItemsList200Response} The populated <code>ShopItemsList200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShopItemsList200Response();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [ResShopItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShopItemsList200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShopItemsList200Response</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                ResShopItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ResShopItem>} items
 */
ShopItemsList200Response.prototype['items'] = undefined;






export default ShopItemsList200Response;

