/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class ShopOrderPaymentMethod.
 * @enum {String}
 * @readonly
 */
const ShopOrderPaymentMethod = {
  /**
   * value: "CASH"
   * @const
   */
  CASH: "CASH",

  /**
   * value: "CARD"
   * @const
   */
  CARD: "CARD",

  /**
   * value: "CHECK"
   * @const
   */
  CHECK: "CHECK",

  /**
   * Returns a <code>ShopOrderPaymentMethod</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/ShopOrderPaymentMethod} The enum <code>ShopOrderPaymentMethod</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ShopOrderPaymentMethod};