/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResShopItem from './ResShopItem';

/**
 * The ShopItemsCreate201Response model module.
 * @module model/ShopItemsCreate201Response
 * @version 0.1.0
 */
class ShopItemsCreate201Response {
    /**
     * Constructs a new <code>ShopItemsCreate201Response</code>.
     * @alias module:model/ShopItemsCreate201Response
     */
    constructor() { 
        
        ShopItemsCreate201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShopItemsCreate201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShopItemsCreate201Response} obj Optional instance to populate.
     * @return {module:model/ShopItemsCreate201Response} The populated <code>ShopItemsCreate201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShopItemsCreate201Response();

            if (data.hasOwnProperty('item')) {
                obj['item'] = ResShopItem.constructFromObject(data['item']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShopItemsCreate201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShopItemsCreate201Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `item`
        if (data['item']) { // data not null
          ResShopItem.validateJSON(data['item']);
        }

        return true;
    }


}



/**
 * @member {module:model/ResShopItem} item
 */
ShopItemsCreate201Response.prototype['item'] = undefined;






export default ShopItemsCreate201Response;

