/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ShopOrderStatus.
* @enum {}
* @readonly
*/
export default class ShopOrderStatus {
    
        /**
         * value: "OPEN"
         * @const
         */
        "OPEN" = "OPEN";

    
        /**
         * value: "CLOSED"
         * @const
         */
        "CLOSED" = "CLOSED";

    
        /**
         * value: "SUBMITTED"
         * @const
         */
        "SUBMITTED" = "SUBMITTED";

    
        /**
         * value: "PAID"
         * @const
         */
        "PAID" = "PAID";

    
        /**
         * value: "CANCELLED"
         * @const
         */
        "CANCELLED" = "CANCELLED";

    
        /**
         * value: "CONFIRMED"
         * @const
         */
        "CONFIRMED" = "CONFIRMED";

    

    /**
    * Returns a <code>ShopOrderStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ShopOrderStatus} The enum <code>ShopOrderStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

