/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ShopPurchaseItemFulfillmentStatus.
* @enum {}
* @readonly
*/
export default class ShopPurchaseItemFulfillmentStatus {
    
        /**
         * value: "PENDING"
         * @const
         */
        "PENDING" = "PENDING";

    
        /**
         * value: "CANCELLED"
         * @const
         */
        "CANCELLED" = "CANCELLED";

    
        /**
         * value: "IN_PROGRESS"
         * @const
         */
        "IN_PROGRESS" = "IN_PROGRESS";

    
        /**
         * value: "FULFILLED"
         * @const
         */
        "FULFILLED" = "FULFILLED";

    

    /**
    * Returns a <code>ShopPurchaseItemFulfillmentStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ShopPurchaseItemFulfillmentStatus} The enum <code>ShopPurchaseItemFulfillmentStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

