/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ShopItemType} from './ShopItemType';

/**
 * The ShopItemsBody model module.
 * @module model/ShopItemsBody
 * @version 0.1.0
 */
export class ShopItemsBody {
  /**
   * Constructs a new <code>ShopItemsBody</code>.
   * @alias module:model/ShopItemsBody
   * @class
   * @param name {String} 
   * @param type {module:model/ShopItemType} 
   */
  constructor(name, type) {
    this.name = name;
    this.type = type;
  }

  /**
   * Constructs a <code>ShopItemsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShopItemsBody} obj Optional instance to populate.
   * @return {module:model/ShopItemsBody} The populated <code>ShopItemsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShopItemsBody();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ShopItemType.constructFromObject(data['type']);
      if (data.hasOwnProperty('info'))
        obj.info = ApiClient.convertToType(data['info'], 'String');
      if (data.hasOwnProperty('amountFee'))
        obj.amountFee = ApiClient.convertToType(data['amountFee'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
ShopItemsBody.prototype.name = undefined;

/**
 * @member {module:model/ShopItemType} type
 */
ShopItemsBody.prototype.type = undefined;

/**
 * @member {String} info
 */
ShopItemsBody.prototype.info = undefined;

/**
 * @member {String} amountFee
 */
ShopItemsBody.prototype.amountFee = undefined;

