/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblyComPublicApi);
  }
}(this, function(expect, MyOhioAssemblyComPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MyOhioAssemblyComPublicApi.AuthPasswordUpdateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthPasswordUpdateRequest', function() {
    it('should create an instance of AuthPasswordUpdateRequest', function() {
      // uncomment below and update the code to test AuthPasswordUpdateRequest
      //var instance = new MyOhioAssemblyComPublicApi.AuthPasswordUpdateRequest();
      //expect(instance).to.be.a(MyOhioAssemblyComPublicApi.AuthPasswordUpdateRequest);
    });

    it('should have the property pass (base name: "pass")', function() {
      // uncomment below and update the code to test the property pass
      //var instance = new MyOhioAssemblyComPublicApi.AuthPasswordUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property passConf (base name: "passConf")', function() {
      // uncomment below and update the code to test the property passConf
      //var instance = new MyOhioAssemblyComPublicApi.AuthPasswordUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property elevatedPass (base name: "elevatedPass")', function() {
      // uncomment below and update the code to test the property elevatedPass
      //var instance = new MyOhioAssemblyComPublicApi.AuthPasswordUpdateRequest();
      //expect(instance).to.be();
    });

    it('should have the property elevatedPassConf (base name: "elevatedPassConf")', function() {
      // uncomment below and update the code to test the property elevatedPassConf
      //var instance = new MyOhioAssemblyComPublicApi.AuthPasswordUpdateRequest();
      //expect(instance).to.be();
    });

  });

}));
