/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblycomPublicApi);
  }
}(this, function(expect, MyOhioAssemblycomPublicApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MemberNationalityStatus', function() {
      beforeEach(function() {
        instance = MyOhioAssemblycomPublicApi.MemberNationalityStatus;
      });

      it('should create an instance of MemberNationalityStatus', function() {
        // TODO: update the code to test MemberNationalityStatus
        expect(instance).to.be.a('object');
      });

      it('should have the property PENDING', function() {
        expect(instance).to.have.property('PENDING');
        expect(instance.PENDING).to.be("PENDING");
      });

      it('should have the property VERIFIED', function() {
        expect(instance).to.have.property('VERIFIED');
        expect(instance.VERIFIED).to.be("VERIFIED");
      });

      it('should have the property DENIED', function() {
        expect(instance).to.have.property('DENIED');
        expect(instance.DENIED).to.be("DENIED");
      });

    });
  });

}));
