/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblyComPublicApi);
  }
}(this, function(expect, MyOhioAssemblyComPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MembersCreateRequest', function() {
    it('should create an instance of MembersCreateRequest', function() {
      // uncomment below and update the code to test MembersCreateRequest
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be.a(MyOhioAssemblyComPublicApi.MembersCreateRequest);
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property passwordConf (base name: "passwordConf")', function() {
      // uncomment below and update the code to test the property passwordConf
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property recordingSecretaryEmail (base name: "recordingSecretaryEmail")', function() {
      // uncomment below and update the code to test the property recordingSecretaryEmail
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property coordinatorEmail (base name: "coordinatorEmail")', function() {
      // uncomment below and update the code to test the property coordinatorEmail
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property middleName (base name: "middleName")', function() {
      // uncomment below and update the code to test the property middleName
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property dob (base name: "dob")', function() {
      // uncomment below and update the code to test the property dob
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property addrLine1 (base name: "addrLine1")', function() {
      // uncomment below and update the code to test the property addrLine1
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property addrLine2 (base name: "addrLine2")', function() {
      // uncomment below and update the code to test the property addrLine2
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property addrCity (base name: "addrCity")', function() {
      // uncomment below and update the code to test the property addrCity
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property addrState (base name: "addrState")', function() {
      // uncomment below and update the code to test the property addrState
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property addrZip (base name: "addrZip")', function() {
      // uncomment below and update the code to test the property addrZip
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property addrCounty (base name: "addrCounty")', function() {
      // uncomment below and update the code to test the property addrCounty
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

    it('should have the property emailAlt (base name: "emailAlt")', function() {
      // uncomment below and update the code to test the property emailAlt
      //var instance = new MyOhioAssemblyComPublicApi.MembersCreateRequest();
      //expect(instance).to.be();
    });

  });

}));
