/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblycomPublicApi);
  }
}(this, function(expect, MyOhioAssemblycomPublicApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ResAccount', function() {
      beforeEach(function() {
        instance = new MyOhioAssemblycomPublicApi.ResAccount();
      });

      it('should create an instance of ResAccount', function() {
        // TODO: update the code to test ResAccount
        expect(instance).to.be.a(MyOhioAssemblycomPublicApi.ResAccount);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property email (base name: "email")', function() {
        // TODO: update the code to test the property email
        expect(instance).to.have.property('email');
        // expect(instance.email).to.be(expectedValueLiteral);
      });

      it('should have the property role (base name: "role")', function() {
        // TODO: update the code to test the property role
        expect(instance).to.have.property('role');
        // expect(instance.role).to.be(expectedValueLiteral);
      });

      it('should have the property isChangePassword (base name: "isChangePassword")', function() {
        // TODO: update the code to test the property isChangePassword
        expect(instance).to.have.property('isChangePassword');
        // expect(instance.isChangePassword).to.be(expectedValueLiteral);
      });

      it('should have the property isBlocked (base name: "isBlocked")', function() {
        // TODO: update the code to test the property isBlocked
        expect(instance).to.have.property('isBlocked');
        // expect(instance.isBlocked).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property deletedAt (base name: "deletedAt")', function() {
        // TODO: update the code to test the property deletedAt
        expect(instance).to.have.property('deletedAt');
        // expect(instance.deletedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
