/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblyComPublicApi);
  }
}(this, function(expect, MyOhioAssemblyComPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MyOhioAssemblyComPublicApi.ResMemberDoc();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ResMemberDoc', function() {
    it('should create an instance of ResMemberDoc', function() {
      // uncomment below and update the code to test ResMemberDoc
      //var instance = new MyOhioAssemblyComPublicApi.ResMemberDoc();
      //expect(instance).to.be.a(MyOhioAssemblyComPublicApi.ResMemberDoc);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MyOhioAssemblyComPublicApi.ResMemberDoc();
      //expect(instance).to.be();
    });

    it('should have the property ownerId (base name: "ownerId")', function() {
      // uncomment below and update the code to test the property ownerId
      //var instance = new MyOhioAssemblyComPublicApi.ResMemberDoc();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MyOhioAssemblyComPublicApi.ResMemberDoc();
      //expect(instance).to.be();
    });

    it('should have the property signedUrl (base name: "signedUrl")', function() {
      // uncomment below and update the code to test the property signedUrl
      //var instance = new MyOhioAssemblyComPublicApi.ResMemberDoc();
      //expect(instance).to.be();
    });

    it('should have the property sizeMb (base name: "sizeMb")', function() {
      // uncomment below and update the code to test the property sizeMb
      //var instance = new MyOhioAssemblyComPublicApi.ResMemberDoc();
      //expect(instance).to.be();
    });

  });

}));
