/*
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * OpenAPI spec version: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblycomPublicApi);
  }
}(this, function(expect, MyOhioAssemblycomPublicApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ResShopPurchaseItem', function() {
      beforeEach(function() {
        instance = new MyOhioAssemblycomPublicApi.ResShopPurchaseItem();
      });

      it('should create an instance of ResShopPurchaseItem', function() {
        // TODO: update the code to test ResShopPurchaseItem
        expect(instance).to.be.a(MyOhioAssemblycomPublicApi.ResShopPurchaseItem);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property fulfillmentStatus (base name: "fulfillmentStatus")', function() {
        // TODO: update the code to test the property fulfillmentStatus
        expect(instance).to.have.property('fulfillmentStatus');
        // expect(instance.fulfillmentStatus).to.be(expectedValueLiteral);
      });

      it('should have the property orderId (base name: "orderId")', function() {
        // TODO: update the code to test the property orderId
        expect(instance).to.have.property('orderId');
        // expect(instance.orderId).to.be(expectedValueLiteral);
      });

      it('should have the property orderItem (base name: "orderItem")', function() {
        // TODO: update the code to test the property orderItem
        expect(instance).to.have.property('orderItem');
        // expect(instance.orderItem).to.be(expectedValueLiteral);
      });

      it('should have the property feePaid (base name: "feePaid")', function() {
        // TODO: update the code to test the property feePaid
        expect(instance).to.have.property('feePaid');
        // expect(instance.feePaid).to.be(expectedValueLiteral);
      });

      it('should have the property notes (base name: "notes")', function() {
        // TODO: update the code to test the property notes
        expect(instance).to.have.property('notes');
        // expect(instance.notes).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "createdAt")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updatedAt")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property deletedAt (base name: "deletedAt")', function() {
        // TODO: update the code to test the property deletedAt
        expect(instance).to.have.property('deletedAt');
        // expect(instance.deletedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
