/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblyComPublicApi);
  }
}(this, function(expect, MyOhioAssemblyComPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MyOhioAssemblyComPublicApi.DocsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocsApi', function() {
    describe('credentialCardsGetOne', function() {
      it('should call credentialCardsGetOne successfully', function(done) {
        //uncomment below and update the code to test credentialCardsGetOne
        //instance.credentialCardsGetOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberDocsCreate', function() {
      it('should call memberDocsCreate successfully', function(done) {
        //uncomment below and update the code to test memberDocsCreate
        //instance.memberDocsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberDocsDeleteOne', function() {
      it('should call memberDocsDeleteOne successfully', function(done) {
        //uncomment below and update the code to test memberDocsDeleteOne
        //instance.memberDocsDeleteOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberDocsDownload', function() {
      it('should call memberDocsDownload successfully', function(done) {
        //uncomment below and update the code to test memberDocsDownload
        //instance.memberDocsDownload(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberDocsGet', function() {
      it('should call memberDocsGet successfully', function(done) {
        //uncomment below and update the code to test memberDocsGet
        //instance.memberDocsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberDocsNameUpdateOne', function() {
      it('should call memberDocsNameUpdateOne successfully', function(done) {
        //uncomment below and update the code to test memberDocsNameUpdateOne
        //instance.memberDocsNameUpdateOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberDocsUpdateOne', function() {
      it('should call memberDocsUpdateOne successfully', function(done) {
        //uncomment below and update the code to test memberDocsUpdateOne
        //instance.memberDocsUpdateOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
