/**
 * MyOhioAssembly.com Public API
 * REST API for MyOhioAssembly.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@myohioassembly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MyOhioAssemblyComPublicApi);
  }
}(this, function(expect, MyOhioAssemblyComPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MyOhioAssemblyComPublicApi.MemberProfilesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MemberProfilesApi', function() {
    describe('memberProfileDocsCreate', function() {
      it('should call memberProfileDocsCreate successfully', function(done) {
        //uncomment below and update the code to test memberProfileDocsCreate
        //instance.memberProfileDocsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberProfileDocsDeleteOne', function() {
      it('should call memberProfileDocsDeleteOne successfully', function(done) {
        //uncomment below and update the code to test memberProfileDocsDeleteOne
        //instance.memberProfileDocsDeleteOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberProfileDocsNameUpdateOne', function() {
      it('should call memberProfileDocsNameUpdateOne successfully', function(done) {
        //uncomment below and update the code to test memberProfileDocsNameUpdateOne
        //instance.memberProfileDocsNameUpdateOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberProfileDocsUpdateOne', function() {
      it('should call memberProfileDocsUpdateOne successfully', function(done) {
        //uncomment below and update the code to test memberProfileDocsUpdateOne
        //instance.memberProfileDocsUpdateOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberProfileGet', function() {
      it('should call memberProfileGet successfully', function(done) {
        //uncomment below and update the code to test memberProfileGet
        //instance.memberProfileGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('memberProfileUpdate', function() {
      it('should call memberProfileUpdate successfully', function(done) {
        //uncomment below and update the code to test memberProfileUpdate
        //instance.memberProfileUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
